# Generated by Django 5.2.6 on 2025-09-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='catagory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
